apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: app
          image: hello-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ip-logs
              mountPath: /logs/
      volumes:
        - name: ip-logs
          persistentVolumeClaim:
            claimName: ip-logs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30950
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ip-logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ip-logs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual